services:
  webdatademo:
    image: ${DOCKER_REGISTRY-}webdatademo
    build:
      context: .
      dockerfile: WebDataDemo/Dockerfile
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y